const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),HOST='0.0.0.0',ROOT=__dirname,DB=path.join(ROOT,'data.json');
const ADMIN_USER=process.env.ADMIN_USER||'admin',ADMIN_PASS=process.env.ADMIN_PASS||'change-me-now';
if(process.env.NODE_ENV==='production' && (!process.env.ADMIN_USER || !process.env.ADMIN_PASS || ADMIN_PASS==='change-me-now')){throw new Error('Production requires ADMIN_USER and a strong ADMIN_PASS environment variable');}
const sessions=new Map(), adminSessions=new Map();
const rateBuckets=new Map();
const LOGIN_WINDOW=15*60*1000, LOGIN_MAX=8, SESSION_TTL=12*60*60*1000, BODY_LIMIT=100*1024;
function clientIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()}
function rateLimit(key,windowMs=LOGIN_WINDOW,max=LOGIN_MAX){const t=Date.now(),a=(rateBuckets.get(key)||[]).filter(x=>t-x<windowMs);if(a.length>=max){rateBuckets.set(key,a);return false}a.push(t);rateBuckets.set(key,a);return true}
setInterval(()=>{const t=Date.now();for(const [k,a] of rateBuckets)if(!a.some(x=>t-x<LOGIN_WINDOW))rateBuckets.delete(k);for(const [k,v] of sessions)if(v.expiresAt<t)sessions.delete(k);for(const [k,v] of adminSessions)if(v<t)adminSessions.delete(k)},10*60*1000);
const DAY=86400000;
function read(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch(e){return {settings:{brand:'Grand Crown',currency:'UGX'},products:[],users:[],purchases:[],transactions:[],referrals:[],activity:[],payments:[],withdrawals:[]}}}
function write(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}
function ensure(d){for(const k of ['users','purchases','transactions','referrals','activity','payments','withdrawals','products'])if(!Array.isArray(d[k]))d[k]=[];d.settings=d.settings||{brand:'Grand Crown',currency:'UGX'};let changed=false;for(const p of d.products){if(!p.id){p.id=id('PROD');changed=true}}if(changed)write(d);}
function now(){return new Date().toISOString()}
function id(prefix){return prefix+'-'+crypto.randomBytes(7).toString('hex').toUpperCase()}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return {salt:s,hash:crypto.scryptSync(String(p),s,64).toString('hex')}}
function verify(p,u){try{return crypto.timingSafeEqual(Buffer.from(crypto.scryptSync(String(p),u.passwordSalt,64).toString('hex'),'hex'),Buffer.from(u.passwordHash,'hex'))}catch{return false}}
function referralCode(users){let c;do{c=crypto.randomBytes(4).toString('hex').toUpperCase()}while(users.some(u=>u.referralCode===c));return c}
function userById(d,idv){return d.users.find(u=>String(u.id)===String(idv))}
function sessionUser(req){const m=(req.headers.cookie||'').match(/(?:^|;\s*)gc_user=([^;]+)/);const s=m&&sessions.get(m[1]);if(!s)return null;if(s.expiresAt<Date.now()){sessions.delete(m[1]);return null}return s.userId}
function isAdmin(req){const m=(req.headers.cookie||'').match(/(?:^|;\s*)gc_admin=([^;]+)/);const exp=m&&adminSessions.get(m[1]);if(!exp)return false;if(exp<Date.now()){adminSessions.delete(m[1]);return false}return true}
function sameOrigin(req){const origin=req.headers.origin;if(!origin)return true;const host=req.headers.host;return origin===`http://${host}`||origin===`https://${host}`}
function secureCookie(req){return req.headers['x-forwarded-proto']==='https'||process.env.NODE_ENV==='production'}
function cookie(req,name,value,extra=''){return `${name}=${value}; HttpOnly; Path=/; SameSite=Lax${secureCookie(req)?'; Secure':''}${extra}`}
function send(res,status,type,body,headers={}){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; base-uri 'self'; frame-ancestors 'none'; object-src 'none'; form-action 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';",...(process.env.NODE_ENV==='production'?{'Strict-Transport-Security':'max-age=31536000; includeSubDomains'}:{}),...headers});res.end(body)}
function json(res,status,o,headers){send(res,status,'application/json; charset=utf-8',JSON.stringify(o),headers)}
function parseBody(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>BODY_LIMIT){reject(new Error('Request too large'));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(new Error('Invalid JSON'))}});req.on('error',reject)})}
function serve(res,file){if(!fs.existsSync(file))return json(res,404,{error:'Not found'});const ext=path.extname(file);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};send(res,200,types[ext]||'application/octet-stream',fs.readFileSync(file))}
function publicUser(u){if(!u)return null;const {passwordHash,passwordSalt,...safe}=u;return safe}
function activePurchases(d,uid){return d.purchases.filter(p=>String(p.userId)===String(uid)&&p.status==='active')}
function processEarnings(d){let changed=false;for(const p of d.purchases){if(p.status!=='active'||!p.userId)continue;const prod=d.products.find(x=>String(x.id)===String(p.productId));if(!prod)continue;const days=Number(prod.days||90),daily=Number(prod.daily||0),start=new Date(p.purchasedAt).getTime();if(!Number.isFinite(start)||!daily)continue;const target=Math.min(Math.floor((Date.now()-start)/DAY),days);p.earningsCredited=Number(p.earningsCredited||0);const u=userById(d,p.userId);if(!u)continue;while(p.earningsCredited<target){const day=p.earningsCredited+1;const exists=d.transactions.some(t=>t.type==='daily_earning'&&t.purchaseId===p.id&&t.day===day);if(!exists){u.wallet=Number(u.wallet||0)+daily;u.totalEarned=Number(u.totalEarned||0)+daily;d.transactions.push({id:id('EARN'),userId:u.id,type:'daily_earning',purchaseId:p.id,day,amount:daily,createdAt:now()})}p.earningsCredited=day;changed=true}}if(changed)write(d)}
function applyReferral(d,buyerId,purchaseId,amount){const buyer=userById(d,buyerId);if(!buyer)return;const rates=[.25,.02,.01];let refId=buyer.referredBy;const seen=new Set([String(buyer.id)]);for(let i=0;i<3&&refId;i++){if(seen.has(String(refId)))break;seen.add(String(refId));const r=userById(d,refId);if(!r)break;const level=i+1;if(!d.transactions.some(t=>t.type==='referral_commission'&&t.purchaseId===purchaseId&&String(t.userId)===String(r.id)&&t.level===level)){const commission=Math.round(Number(amount)*rates[i]);r.wallet=Number(r.wallet||0)+commission;r.totalEarned=Number(r.totalEarned||0)+commission;d.transactions.push({id:id('REF'),userId:r.id,type:'referral_commission',purchaseId,level,amount:commission,createdAt:now()})}refId=r.referredBy}}
function requireUser(req,res){const uid=sessionUser(req);if(!uid){json(res,401,{error:'Login required'});return null}return uid}
function requireAdmin(req,res){if(!isAdmin(req)){json(res,401,{error:'Unauthorized'});return false}return true}
function tx(d,uid,type,amount,extra={}){d.transactions.push({id:id('TX'),userId:uid,type,amount,createdAt:now(),...extra})}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),p=url.pathname;let d=read();ensure(d);processEarnings(d);
if(req.method==='GET'&&p==='/')return serve(res,path.join(ROOT,'public','index.html'));if(req.method==='GET'&&p==='/admin')return serve(res,path.join(ROOT,'public','admin.html'));
if(req.method==='GET'&&p==='/api/products')return json(res,200,d.products);if(req.method==='GET'&&p==='/api/settings')return json(res,200,d.settings);
if(req.method==='POST'&&p==='/api/register'){if(!sameOrigin(req))return json(res,403,{error:'Forbidden origin'});const b=await parseBody(req),phone=String(b.phone||'').trim(),pass=String(b.password||''),ref=String(b.referralCode||'').trim().toUpperCase();if(!/^\+?[0-9]{7,15}$/.test(phone)||pass.length<8)return json(res,400,{error:'Phone and password (minimum 8 characters) are required'});if(d.users.some(u=>u.phone===phone))return json(res,409,{error:'Account already exists'});let parent=ref?d.users.find(u=>u.referralCode===ref):null;if(ref&&!parent)return json(res,400,{error:'Invalid referral code'});const pw=hash(pass),u={id:id('USR'),phone,passwordHash:pw.hash,passwordSalt:pw.salt,referralCode:referralCode(d.users),referredBy:parent?parent.id:null,wallet:2100,totalEarned:2100,createdAt:now(),lastCheckin:null};d.users.push(u);tx(d,u.id,'signup_bonus',2100);d.activity.push({id:id('ACT'),userId:u.id,type:'signup',createdAt:now()});write(d);const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{userId:u.id,expiresAt:Date.now()+SESSION_TTL});return json(res,201,{ok:true,user:publicUser(u)},{'Set-Cookie':cookie(req,'gc_user',token,'; Max-Age='+(SESSION_TTL/1000))})}
if(req.method==='POST'&&p==='/api/login'){if(!sameOrigin(req))return json(res,403,{error:'Forbidden origin'});if(!rateLimit('login:'+clientIp(req)))return json(res,429,{error:'Too many login attempts. Try again later.'},{'Retry-After':'900'});const b=await parseBody(req),u=d.users.find(x=>x.phone===String(b.phone||'').trim());if(!u||!verify(String(b.password||''),u))return json(res,401,{error:'Invalid phone or password'});const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{userId:u.id,expiresAt:Date.now()+SESSION_TTL});return json(res,200,{ok:true,user:publicUser(u)},{'Set-Cookie':cookie(req,'gc_user',token,'; Max-Age='+(SESSION_TTL/1000))})}
if(req.method==='POST'&&p==='/api/logout'){const m=(req.headers.cookie||'').match(/(?:^|;\s*)gc_user=([^;]+)/);if(m)sessions.delete(m[1]);res.setHeader('Set-Cookie',cookie(req,'gc_user','', '; Max-Age=0'));return json(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/me'){const uid=sessionUser(req);return json(res,200,{loggedIn:!!uid,user:uid?publicUser(userById(d,uid)):null})}
if(req.method==='POST'&&p==='/api/checkin'){if(!sameOrigin(req))return json(res,403,{error:'Forbidden origin'});const uid=requireUser(req,res);if(!uid)return;const u=userById(d,uid),today=new Date().toISOString().slice(0,10);if(u.lastCheckin===today)return json(res,409,{error:'Daily check-in already claimed'});u.lastCheckin=today;u.wallet=Number(u.wallet||0)+500;u.totalEarned=Number(u.totalEarned||0)+500;tx(d,uid,'checkin',500);write(d);return json(res,200,{ok:true,reward:500,user:publicUser(u)})}
if(req.method==='GET'&&p==='/api/dashboard'){const uid=requireUser(req,res);if(!uid)return;const u=userById(d,uid);const purchases=activePurchases(d,uid);return json(res,200,{user:publicUser(u),purchases,transactions:d.transactions.filter(t=>String(t.userId)===String(uid)).slice(-100).reverse(),canWithdraw:purchases.length>0})}
if(req.method==='GET'&&p==='/api/referral'){const uid=requireUser(req,res);if(!uid)return;const u=userById(d,uid);const direct=d.users.filter(x=>String(x.referredBy)===String(uid));const l1=new Set(d.users.filter(x=>String(x.referredBy)===String(uid)).map(x=>x.id));const l2=new Set(d.users.filter(x=>x.referredBy&&l1.has(x.referredBy)).map(x=>x.id));const l3=new Set(d.users.filter(x=>x.referredBy&&l2.has(x.referredBy)).map(x=>x.id));const members=d.users.filter(x=>l1.has(x.id)||l2.has(x.id)||l3.has(x.id)).map(x=>({id:x.id,phone:x.phone,level:l1.has(x.id)?1:l2.has(x.id)?2:3,createdAt:x.createdAt}));const commissions=d.transactions.filter(t=>String(t.userId)===String(uid)&&t.type==='referral_commission');return json(res,200,{code:u.referralCode,link:`${url.origin}/?ref=${u.referralCode}`,directReferrals:direct.length,teamSize:members.length,members,commissions})}
if(req.method==='POST'&&p==='/api/payments'){if(!sameOrigin(req))return json(res,403,{error:'Forbidden origin'});const uid=requireUser(req,res);if(!uid)return;const b=await parseBody(req),prod=d.products.find(x=>String(x.id)===String(b.productId)),method=String(b.method||''),payer=String(b.payerPhone||'').trim(),tr=String(b.transactionId||'').trim(),amount=Number(b.amount);if(!prod)return json(res,404,{error:'Product not found'});if(!['Airtel Money','MTN Mobile Money','PesaJet'].includes(method))return json(res,400,{error:'Invalid payment method'});if(!/^\+?[0-9]{7,15}$/.test(payer)||!/^[A-Za-z0-9._-]{4,80}$/.test(tr)||!Number.isFinite(amount))return json(res,400,{error:'Payment details are required'});if(amount!==Number(prod.price))return json(res,400,{error:'Amount must exactly match the product price'});if(d.payments.some(x=>x.transactionId.toLowerCase()===tr.toLowerCase()))return json(res,409,{error:'Transaction ID already submitted'});const pay={id:id('PAY'),userId:uid,productId:prod.id,productName:prod.name,amount,method,payerPhone:payer,transactionId:tr,status:'pending',createdAt:now()};d.payments.push(pay);write(d);return json(res,201,{ok:true,paymentId:pay.id,status:'pending'})}
if(req.method==='GET'&&p==='/api/purchases'){const uid=requireUser(req,res);if(!uid)return;return json(res,200,d.purchases.filter(x=>String(x.userId)===String(uid)))}
if(req.method==='POST'&&p==='/api/withdrawals'){if(!sameOrigin(req))return json(res,403,{error:'Forbidden origin'});const uid=requireUser(req,res);if(!uid)return;const b=await parseBody(req),u=userById(d,uid),amount=Number(b.amount),method=String(b.method||''),phone=String(b.phone||'').trim();if(activePurchases(d,uid).length<1)return json(res,403,{error:'Purchase at least 1 approved product to activate withdrawals'});if(!Number.isFinite(amount)||amount<7000)return json(res,400,{error:'Minimum withdrawal is UGX 7,000'});if(amount>Number(u.wallet||0))return json(res,400,{error:'Insufficient wallet balance'});if(!['Airtel Money','MTN Mobile Money'].includes(method)||!phone)return json(res,400,{error:'Withdrawal details are required'});const fee=Math.round(amount*.12),net=amount-fee;u.wallet=Number(u.wallet)-amount;const w={id:id('WD'),userId:uid,amount,fee,netAmount:net,method,phone,status:'pending',createdAt:now()};d.withdrawals.push(w);tx(d,uid,'withdrawal_hold',-amount,{withdrawalId:w.id});write(d);return json(res,201,{ok:true,withdrawal:w})}
if(req.method==='GET'&&p==='/api/withdrawals'){const uid=requireUser(req,res);if(!uid)return;return json(res,200,d.withdrawals.filter(x=>String(x.userId)===String(uid)))}
if(req.method==='POST'&&p==='/api/admin/login'){if(!sameOrigin(req))return json(res,403,{error:'Forbidden origin'});if(!rateLimit('admin-login:'+clientIp(req),LOGIN_WINDOW,5))return json(res,429,{error:'Too many admin login attempts. Try again later.'},{'Retry-After':'900'});const b=await parseBody(req);const safeEq=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)};const ok=safeEq(b.username,ADMIN_USER)&&safeEq(b.password,ADMIN_PASS);if(!ok)return json(res,401,{error:'Invalid login'});const token=crypto.randomBytes(32).toString('hex');adminSessions.set(token,Date.now()+SESSION_TTL);return json(res,200,{ok:true},{'Set-Cookie':cookie(req,'gc_admin',token,'; Max-Age='+(SESSION_TTL/1000))})}
if(req.method==='POST'&&p==='/api/admin/logout'){const m=(req.headers.cookie||'').match(/(?:^|;\s*)gc_admin=([^;]+)/);if(m)adminSessions.delete(m[1]);res.setHeader('Set-Cookie',cookie(req,'gc_admin','', '; Max-Age=0'));return json(res,200,{ok:true})}
if(p.startsWith('/api/admin/')){if(['POST','PUT','DELETE','PATCH'].includes(req.method)&&!sameOrigin(req))return json(res,403,{error:'Forbidden origin'});if(!requireAdmin(req,res))return;if(req.method==='GET'&&p==='/api/admin/dashboard'){const walletBalances=d.users.reduce((a,u)=>a+Number(u.wallet||0),0),totalDeposited=d.payments.filter(x=>x.status==='approved').reduce((a,x)=>a+Number(x.amount||0),0),totalWithdrawn=d.withdrawals.filter(x=>x.status==='paid').reduce((a,x)=>a+Number(x.amount||0),0),totalInvested=d.purchases.filter(x=>x.status==='active').reduce((a,x)=>a+Number(x.amount||0),0);return json(res,200,{users:d.users.length,products:d.products.length,purchases:d.purchases.length,payments:d.payments.filter(x=>x.status==='pending').length,withdrawals:d.withdrawals.filter(x=>x.status==='pending').length,transactions:d.transactions.length,walletBalances,totalDeposited,totalWithdrawn,totalInvested});}if(req.method==='GET'&&p==='/api/admin/referrals')return json(res,200,{commissions:d.transactions.filter(x=>x.type==='referral_commission').length,total:d.transactions.filter(x=>x.type==='referral_commission').reduce((a,x)=>a+Number(x.amount||0),0)});if(req.method==='GET'&&p==='/api/admin/activity')return json(res,200,d.activity.slice().reverse());if(req.method==='GET'&&p==='/api/admin/users')return json(res,200,d.users.map(publicUser));if(req.method==='GET'&&p==='/api/admin/products')return json(res,200,d.products);if(req.method==='GET'&&p==='/api/admin/transactions')return json(res,200,d.transactions);if(req.method==='GET'&&p==='/api/admin/payments')return json(res,200,d.payments);if(req.method==='GET'&&p==='/api/admin/withdrawals')return json(res,200,d.withdrawals);if(req.method==='GET'&&p==='/api/admin/settings')return json(res,200,d.settings);
if(req.method==='PUT'&&p.startsWith('/api/admin/payments/')){const pay=d.payments.find(x=>x.id===decodeURIComponent(p.split('/').pop()));if(!pay)return json(res,404,{error:'Payment not found'});const b=await parseBody(req),action=String(b.action||'').toLowerCase();if(pay.status!=='pending')return json(res,409,{error:'Payment already reviewed'});if(!['approve','reject'].includes(action))return json(res,400,{error:'Invalid action'});pay.status=action==='approve'?'approved':'rejected';pay.reviewedAt=now();if(action==='approve'){const purchase={id:id('PUR'),paymentId:pay.id,userId:pay.userId,productId:pay.productId,productName:pay.productName,amount:pay.amount,status:'active',purchasedAt:now(),earningsCredited:0};d.purchases.push(purchase);tx(d,pay.userId,'purchase',pay.amount,{paymentId:pay.id,purchaseId:purchase.id});applyReferral(d,pay.userId,purchase.id,pay.amount)}write(d);return json(res,200,{ok:true,payment:pay})}
if(req.method==='PUT'&&p.startsWith('/api/admin/withdrawals/')){const w=d.withdrawals.find(x=>x.id===decodeURIComponent(p.split('/').pop()));if(!w)return json(res,404,{error:'Withdrawal not found'});const b=await parseBody(req),action=String(b.action||'').toLowerCase();if(w.status!=='pending')return json(res,409,{error:'Withdrawal already reviewed'});if(!['approve','reject'].includes(action))return json(res,400,{error:'Invalid action'});w.status=action==='approve'?'paid':'rejected';w.reviewedAt=now();if(action==='reject'){const u=userById(d,w.userId);if(u)u.wallet=Number(u.wallet||0)+Number(w.amount);tx(d,w.userId,'withdrawal_refund',Number(w.amount),{withdrawalId:w.id})}else tx(d,w.userId,'withdrawal_paid',-Number(w.amount),{withdrawalId:w.id,netAmount:w.netAmount});write(d);return json(res,200,{ok:true,withdrawal:w})}
if(req.method==='POST'&&p==='/api/admin/products'){const b=await parseBody(req),x={id:id('PROD'),name:String(b.name||''),price:Number(b.price),daily:Number(b.daily),total:Number(b.total),days:Number(b.days)};if(!x.name||![x.price,x.daily,x.total,x.days].every(Number.isFinite))return json(res,400,{error:'Invalid product'});d.products.push(x);write(d);return json(res,201,x)}
if(req.method==='PUT'&&p.startsWith('/api/admin/products/')){const i=d.products.findIndex(x=>x.id===decodeURIComponent(p.split('/').pop()));if(i<0)return json(res,404,{error:'Product not found'});const b=await parseBody(req);d.products[i]={...d.products[i],...b,price:Number(b.price??d.products[i].price),daily:Number(b.daily??d.products[i].daily),total:Number(b.total??d.products[i].total),days:Number(b.days??d.products[i].days)};write(d);return json(res,200,d.products[i])}
if(req.method==='DELETE'&&p.startsWith('/api/admin/products/')){const i=d.products.findIndex(x=>x.id===decodeURIComponent(p.split('/').pop()));if(i<0)return json(res,404,{error:'Product not found'});d.products.splice(i,1);write(d);return json(res,200,{ok:true})}
if(req.method==='PUT'&&p==='/api/admin/settings'){const b=await parseBody(req);d.settings={...d.settings,...b};write(d);return json(res,200,d.settings)}
}
return json(res,404,{error:'Not found'});}catch(e){console.error(e);return json(res,e.message==='Request too large'?413:500,{error:e.message==='Request too large'?'Request too large':'Server error'})}});
setInterval(()=>{try{processEarnings(read())}catch(e){console.error(e)}},60000);
server.listen(PORT,HOST,()=>console.log(`Grand Crown running on ${HOST}:${PORT}`));
